export const languageMap: Record<string, string> = {
  javascript: "javascript",
  typescript: "typescript",
  react: "javascript",
  node: "javascript",
  html: "html",
  css: "css",
  scss: "scss",
  json: "json",
  markdown: "markdown",
  sql: "sql",
  csharp: "csharp",
  python: "python",
  java: "java",
  go: "go",
  rust: "rust",
  php: "php",
  shell: "shell",
  yaml: "yaml",
  xml: "xml",
};